### ISSUE TITLE
CloudFlare Issue 

### ISSUE THREAD

**Issue by programerr01** [zebpay/zeb_py#3]
First of all, when using this library code it's giving error with json cause the result is not returning in json and giving cloudflare error in return 
Second, how can we know otp beforehand. 
Third, what's the purpose of the api keys when you are going to use login and otp. Please remove the library if you can't maintain it. 
I think the api itself is broken.
Totally unprofessional code

**Comment by sarmahsubham** [comment]
1. Using the url "https://www.zebapi.com/api/v1/" solved my 404 error
2. I made changes to the code and am directly feeding the access token generated from the UI (We had to contact support and they asked us to generate the access token and use it in our code rather than generating it through the code.)
3. I think its a regulation issue, since this is redundant and otp is required, I would suggest directly generate the access token from the UI.

Just remove all the otp and pin parts, feed the access token directly, it should work.

**Comment by programerr01** [comment]
> 1. Using the url "https://www.zebapi.com/api/v1/" solved my 404 error
> 2. I made changes to the code and am directly feeding the access token generated from the UI (We had to contact support and they asked us to generate the access token and use it in our code rather than generating it through the code.)
> 3. I think its a regulation issue, since this is redundant and otp is required, I would suggest directly generate the access token from the UI.
> 
> Just remove all the otp and pin parts, feed the access token directly, it should work.

thanks , i used zebpay rest api instead of this library

**Comment by sarmahsubham** [comment]
Whats the difference? Can you point me to the documentation? Isnt this library just accessing the rest api?

**Comment by programerr01** [comment]
@CaptMcTavish  the way i solved the issue is going directly to the developer page and getting access-token from there instead of doing these steps like login, pin, otp etc. i don't understand why so many steps involved   to get access-token

**Comment by sarmahsubham** [comment]
Yes even they asked me to use the access token directly, I have been using their support email for communication. It seems they still have not figured out whats causing these errors.
